### ISSUE TITLE
Standard Embed

### ISSUE THREAD

**Issue by BronzW** [AgeOfEternity/AgeOfEternity#2]
We need to have a standard style of how we are going to style our embeds, and implement an API to easily create with our chosen style. We need to select:

- [x] Info color and style
- [x] Error color
- [x] Question color
- [x] Help message color
- [x] Default author title (Info - My Epic Embed, for example)
- [x] Default title
- [x] API for creating embeds

**Comment by jw2476** [comment]
Is there a branch you are doing this in?

**Comment by BronzW** [comment]
I will be creating a branch

**Comment by jw2476** [comment]
Colors

- Info: #209CEE
- Error: #FF3860
- Questions: #209CEE
- Help: #00D1B2
- Warning: #FFDD57

**Comment by BronzW** [comment]
Yeah can you create an embed branch?

**Comment by BronzW** [comment]
Or i'll just push to main

**Comment by BronzW** [comment]
This is done now, might need some chantges and improvements in the future, but works for now.
